puts "🎨 Seeding arts..."
Art.create(id: 1, title: "Starry Night", medium: "Oil on canvas", description: "A view of Saint-Rémy-de-Provence just before sunrise, with an imaginary picturesque village.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1200px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", price: 10000, timestamp: "", user_id: 1)
Art.create(id: 2, title: "The Bedroom", medium: "Oil on canvas", description: "A depiction of a quaint, restful room meant to put the mind at rest.", image: "https://iiif.micr.io/ZKSPH/full/1280,/0/default.jpg", price: 10000, timestamp: "", user_id: 1)
Art.create(id: 3, title: "Study of feathers", medium: "Watercolor", description: "A study of feathers.", image: "https://sothebys-md.brightspotcdn.com/dims4/default/ef4dc93/2147483647/strip/true/crop/2000x1356+0+0/resize/2048x1389!/quality/90/?url=http%3A%2F%2Fsothebys-brightspot.s3.amazonaws.com%2Fmedia-desk%2F00%2F6d%2F6b794c4541b1bb13ab6c97f3d4ec%2Fl21040-bxj29-01-group-01.jpg", price: 25, timestamp: "", user_id: 2)
Art.create(id: 4, title: "Portrait of a young woman", medium: "Gouache on paper", description: "Portrait of a young woman.", image: "https://image.invaluable.com/housePhotos/bonhamsarchive/49/276149/H0267-L13363685.jpg", price: 100, timestamp: "", user_id: 2)
Art.create(id: 5, title: "The Ugly Duchess", medium: "Oil on canvas", description: "A fine woman woman, dressed in the finest clothes and holding the prettiest flower.", image: "https://www≈.zbrushcentral.com/uploads/default/original/4X/4/2/3/4232fa367c1e26f78a83c1280a6c2e5652a5ad9b.jpeg", price: 20000, timestamp: "", user_id: 3)
Art.create(id: 6, title: "Ill-Matched Lovers", medium: "Oil on panel", description: "A depiction of time making fools of us all, either by having too much or not enough.", image: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Quentin_Massys_-_Ill-Matched_Lovers%2C_c._1520-25.jpg", price: 25000, timestamp: "", user_id: 3)
Art.create(id: 7, title: "Le Regard oblique", medium: "6 Vintage gelatin silver prints", description: "Taken in a Paris shop window in 1948.", image: "https://www.art.salon/images/robert-doisneau_le-regard-oblique-vitrine-de-romi-paris_AID526798.jpg?f=grey", price: 125, timestamp: "", user_id: 4)
Art.create(id: 8, title: "Man Looking at Painting of a Nude", medium: "silver gelatin print", description: "Taken in a Paris shop window in 1949.", image: "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&width=668&height=800&quality=80&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FhH6vbR98eZgiTwmzA6b3aA%2Fnormalized.jpg", price: 125, timestamp: "", user_id: 4)
Art.create(id: 9, title: "Woman with Dead Child", medium: "Etching with chine collé", description: "Despair.", image: "https://upload.wikimedia.org/wikipedia/commons/1/10/Kaethe_Kollwitz_-_Frau_mit_totem_Kind.jpg", price: 800, timestamp: "", user_id: 5)
Art.create(id: 10, title: "Woman Entrusts Herself to Death", medium: "Lithograph", description: "Death.", image: "https://www.moma.org/media/W1siZiIsIjExNzAzMiJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MTQ0MFx1MDAzZSJdXQ.jpg?sha=dd1a6fbba13aa031", price: 850, timestamp: "", user_id: 5)
puts "👨🏽‍🎤 Seeding users..."
User.create(id: 1, name: "Vincent Van Gogh", username: "StarryNightGuy", email: "StarryNightGuy@gmail.com", password: "ArtIsCool", bio: "Prolific Dutch post-impressionist artist.", image: "https://cdn.britannica.com/36/69636-050-81A93193/Self-Portrait-artist-panel-board-Vincent-van-Gogh-1887.jpg")
User.create(id: 2, name: "Sarah Biffen", username: "PaintPotato", email: "iispotato@gmail.com", password: "ArtIsCool", bio: "Painter, woman, starving potato.", image: "https://artlogic-res.cloudinary.com/w_1400,h_1400,c_limit,f_auto,fl_lossy,q_auto:good/ws-philipmould/usr/images/news/hero_image/13/sarah-biffin-sothebys.jpg")
User.create(id: 3, name: "Quentin Matsys", username: "Mag1", email: "TheDuchess@gmail.com", password: "ArtIsCool", bio: "Creating new schools of painting.", image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Jan_Wierix_002.jpg")
User.create(id: 4, name: "Robert Doisneau", username: "ThatPhotoGuy", email: "ParisPhotography@gmail.com", password: "ArtIsCool", bio: "Photographer, photojournalist, humanist.", image: "https://www.robert-doisneau.com/ressources/images/5/182,doisneau-hamilton.jpg")
User.create(id: 5, name: "Käthe Kollwitz", username: "DeadBabyArtist", email: "CharcoalLady@gmail.com", password: "ArtIsCool", bio: "Painter of life and all of its despairs.", image: "https://www.moma.org/d/assets/W1siZiIsIjIwMTYvMDUvMjcvYmFvZ2o3Y21vXzMyMDFfMjQxMjA5X2tvbGx3aXR6LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ/3201_241209_kollwitz.jpg?sha=498b197fcafe7914")
User.create(id: 10, name: "Test User", username: "phase3proj", email: "fakeemail@gmail.com", password: "ArtIsCool", bio: "Not a real artist", image: 'https://static.boredpanda.com/blog/wp-content/uploads/2018/03/ugly-medieval-cats-art-103-5aafaff5c7b63__700.jpg')
puts "✅ Done seeding!"